# Generated by Django 3.0.6 on 2020-05-23 17:36

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, default=None, null=True)),
                ('y', models.FloatField(blank=True, default=None, null=True)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Line_String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linienSegment', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('end_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='application1.Point')),
                ('start_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='application1.Point')),
            ],
        ),
    ]
