# Generated by Django 3.0.6 on 2020-05-23 18:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_string',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='line_string',
            name='start_point',
        ),
        migrations.AddField(
            model_name='line_string',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='line_string',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='line_string',
            name='linienSegment',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
