# Generated by Django 3.0.6 on 2020-05-31 21:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_auto_20200531_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_string',
            name='linienSegment',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, default=None, null=True, srid=25832),
        ),
    ]
