# Generated by Django 3.0.3 on 2020-06-03 19:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0004_auto_20200531_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_string',
            old_name='personel_id',
            new_name='personal_id',
        ),
        migrations.AddField(
            model_name='line_string',
            name='buffer',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=25832),
        ),
        migrations.AddField(
            model_name='line_string',
            name='end_point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='application1.Point'),
        ),
        migrations.AddField(
            model_name='line_string',
            name='start_point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='application1.Point'),
        ),
    ]
