# Generated by Django 3.0.3 on 2020-06-03 19:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0005_auto_20200603_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_string',
            old_name='buffer',
            new_name='buffer_geom',
        ),
        migrations.RenameField(
            model_name='line_string',
            old_name='linienSegment',
            new_name='line_geom',
        ),
        migrations.AddField(
            model_name='point',
            name='point_geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=25832),
        ),
    ]
