# Generated by Django 3.0.3 on 2020-06-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0006_auto_20200603_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KML_File',
        ),
    ]
