# Generated by Django 3.0.3 on 2020-06-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0007_delete_kml_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='line_string',
            unique_together={('start_point', 'end_point')},
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('x', 'y', 'time_stamp')},
        ),
    ]
